name: Python Test
defaults:
  run:
    working-directory: python-env
on:
  [push, pull_request]:
    branches: [ $default-branch, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install requirements.txt
        python -m pip install flake8
    - name: Test Pytest
      run: |
        pytest
    
